# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luca M Jones | Photography
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Photographs by Luca Messenger-Jones
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://192.168.0.5:4000/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luca_mj

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-timeago
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock

jekyll_timeago:
  depth: 1 # Level of detail
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      fstop: "-"
      iso: "-"
      shutterspeed: "-"
      
sass:
    style: compressed